# This module allows you to generate a file with basic authentication credentials for use with Apache Webserver ea
class basicauth (
    $owner      = 'www-data',
    $group      = 'www-data',
    $mode       = '0600',
    $location   = '/var/www/.basicauth',
    $ensure     = 'absent', # Do not do anything unless explicitly enabled 
)
{
    if $ensure == 'present' {
        $entry = hiera('basicauth::basic_entry', {})
        create_resources('basicauth::basic_entry', $entry)
        concat { $location:
            owner => $owner,
            group => $group,
            mode  => $mode,
        }
        concat::fragment{ 'file-header':
            target  => $location,
            content => "#This file is generated by Puppet, do not change manually!\n",
            order   => '01',
        }
    }
    elsif $ensure == 'absent' {
        $entry = hiera('basicauth::basic_entry', {})
        file { $location:
            ensure => 'absent',
            force  => true
        }
    }

     # tried to test vault lookup module, but we don't have a vault server and the 
     # dev option doesn't do SSL and stuff... 
     
    # $d = Deferred('vault_lookup::lookup', ["secret/basic_auth", 'http://puppet.vagrant.lan:8200'])

    # notify { example :
    #     message => $d
    # }
}
